api:
  base:
    url: "http://localhost:8080/api"

loo:
  ids:
    - 1
    - 2

people:
  count: 10
  use_toilet_seconds: 5

logging:
  level:
    io.github.shanepark.mockloo.loolock.controller: DEBUG
