api:
  base:
    url: "http://localhost:8080/api"

loo:
  ids:
    - 1F Men
    - 1F Women1
    - 1F Women2
    - 2F Window
    - 2F Aisle1
    - 2F Aisle2

people:
  count: 30
  use_toilet_seconds: 5

logging:
  level:
    io.github.shanepark.mockloo.loolock.controller: DEBUG
